import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "../styles/globals.css"
import { Providers } from './providers'
import { usePathname } from 'next/navigation'
import NavBar from '../components/navbar'
import Footer from '../components/footer'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CertiSearch',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <header >
          <NavBar />
        </header>


        <Providers>{children}</Providers>
        <Footer />
      </body>


    </html>
  )
}
